### ISSUE TITLE
Bug: linking sometimes goes wrong

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#143]
We see that linking sometimes goes wrong: a new author, translator or uploaded file is created, but the link to the publication is not made correctly.

Characteristics of the problem:
* This seems to be related to the stub system, as it appears this does not appear when clicking edit. 
* This seems to be related to multiple people working a stub simultaneously, as Matija's publication got linked to a stub created by Jan.

Linking a stub to an individual user, and making sure each user has only stub 'open', as suggested in #138 , might also be (part of the) solution here?

Because of the unstable behavior, this one is hard to reproduce... but perhaps if we try multiple times, we can 'catch' one while have the Chrome debug tools open?

**Comment by Mergpijp** [comment]
The system were the old publication gets copied to a new publication should be solved. This way a stub becomes a non stub and people can work simultaneously. Will look into this.

**Comment by Mergpijp** [comment]
Like we discussed I now take highest pk from created_by user and the pk is not the form instance.

**Comment by Elisagig** [comment]
Please follow up. This problem is still happening every now and then. Less often but happening again

**Comment by Mergpijp** [comment]
Okay how then would I reproduce this problem?

**Comment by Woseseltops** [comment]
Possible way to reproduce: use the incognito mode of your browser to log in as another user simultaneously.

**Comment by Mergpijp** [comment]
Did as @Woseseltops said. @Elisagig  are you sure this issue persists? I cant reproduce it.

**Comment by Mergpijp** [comment]
Are some users sharing accounts that you know of?

**Comment by Elisagig** [comment]
Not that I know of. But for future I mean, when it becomes public
