### ISSUE TITLE
Permission error and missing paragraph

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#212]
My colleague Chris, informed me this 5 minutes ago @Woseseltops 
"Just an update that nearly every single book I added has both the permission error and a missing photograph. A couple have the photography but still have the permission error. One or two seem to have the wrong photograph as the main photograph. I’m not sure if there is something consistently wrong that I did when adding to the database or if maybe there is something affecting books that were added around the same time, but almost none of the books I added I am able to edit…"

**Comment by Woseseltops** [comment]
Hey @Elisagig , so if I'm not mistaken, there are 4 separate issues:

1. Chris: permission problem
2. Chris: missing photographs
3. Chris: photographs mixed up
4. Habtom: an error 

I think problem 1 should be solved now, at least temporarily (see #211), and problem 2 might also have been caused by this. Not sure about problem 3 and 4, though, can you help me reproduce them on my computer? Things that would help
* Links to the pages that the error message or problem
* Step by step instructions to reproduce the problem

Thanks

**Comment by Elisagig** [comment]
Thanks. Will ask my colleagues tomorrow morning in the meeting and get back to you @Woseseltops

**Comment by Elisagig** [comment]
Dear @Woseseltops this problem is still there. the two publications have somehow merged in a weird way. Kindly fix! Thanks

**Comment by Woseseltops** [comment]
Okay I have managed to reproduce:
* The missing images problem: https://github.com/Mergpijp/GlobalOrthodoxy/issues/214
* The 'First' button link problem by Habtom: https://github.com/Mergpijp/GlobalOrthodoxy/issues/215
