### ISSUE TITLE
When adding a new UploadedFile, it should be visible at the publication you started from immediately

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#62]
Quote from Heleen, talking about uploaded files:

> Another issue is that in some cases, I wasn't able to connect the right publication under 'publications' - I was sure to have selected the right one, and then it unexplicably connected another publication - making the photograph of course disappear from where it should be.

**Comment by Woseseltops** [comment]
@Mergpijp , can you add a few uploaded files and try to link the, to see if you can reproduce this problem?

**Comment by Mergpijp** [comment]
Well this bug should be resolved recently because if the user adds a publication to the uploaded file which already had a publication added; the publication would not change because it looks at length differences. I fixed this recently. Hope this is the same thing we are talking about

**Comment by Elisagig** [comment]
Hi guys,my colleagues are saying they still have a problem that they say they formerly reported and is the following: When they go to **Files**, then **Choose**, they see something that says "**The Results Could Not be Loaded"**, and then at the end when they view the publication they see a wrong publication linked at the end under "publications". Could you please remind me if this was deployed? Thaks @Woseseltops @Mergpijp

**Comment by Woseseltops** [comment]
Steps to reproduce:
* Select an existing publication, like https://globalorthodoxy.cls.ru.nl/publication/31/edit/
* Go to the files tab and click the plus icon to create a new uploaded file .
* Upload a file and select the exiting publication from the list.
* Click save

Expected behavior: 
* Popup closes
* In my previous main window the newly created  file is visible in the 'Uploaded files' field.

What happens instead: 
* I'm redirected to the uploaded file list inside the popup.
* The 'Uploaded files' field in the original main browser is still empty.
* When I look up the newly created uploaded file, it is linked to the publication with id 1 instead.

**Comment by Woseseltops** [comment]
Also, it's good to mention that this problem is making the team less efficient, so this problem has highest priority.

**Comment by Elisagig** [comment]
Yes please. We appreciate it.

**Comment by Mergpijp** [comment]
Hi, some behavior is expected. Alle popups return to the main list. I think the publication field in the Uploaded file popup is the mistake. I tried adding the publication in uploaded file popup and once I refresh the main page it is there. So I cannot reproduce  the part where the uploaded file is connected to the publication with id = 1. 
My proposal is to remove publication from uploaded file and give the image title a good name so that you can retrieve it again when selecting Uploaded files in the main page. (This is were the select2 redis server was build for). This would solve #67 to.

**Comment by Woseseltops** [comment]
> Alle popups return to the main list. 

I know, but a popup is only created as a temporary sidestep from adding a new publication, right? Wouldn't it make more sense if the popup closes once you are done with the sidestep? 

> I think the publication field in the Uploaded file popup is the mistake. I tried adding the publication in uploaded file popup and once I refresh the main page it is there. So I cannot reproduce the part where the uploaded file is connected to the publication with id = 1.

Have you tried following the steps I describe above? Because I still have the problem, following these steps. If you cannot reproduce, let me know, and we'll plan a virtual meeting so I can show you.

> My proposal is to remove publication from uploaded file

Removing or prefilling would both be okay; the main point is that the user doesn't have to select the publication again, as the application should be able to figure this out itself; but this is indeed issue #67 

> give the image title a good name so that you can retrieve it again when selecting Uploaded files in the main page.

For the end user it does not matter whether you make the connection through the filename or through the Django model; as long as the uploaded file is connected to the correct publication!

**Comment by Mergpijp** [comment]
Okay I agree with you on all points but one. Returning back to the list page. Since tagging now happens below in the select2 field it is nice to add new files faster. Afterwards the user can add all files to the publication.

**Comment by Woseseltops** [comment]
Hmm not sure if I understand you correctly here; I'll contact you via email for a live meeting to get our minds aligned.

**Comment by Woseseltops** [comment]
Our idea: remove the popups, work with modals instead. The modals should be able to communicate back the UploadedFile that was created.

**Comment by Woseseltops** [comment]
Extra idea: add an extra button besides the plus button, where we can slowly work towards replicating the same functionality in a modal. Once the extra button can do everything, the plus can be removed.

**Comment by Elisagig** [comment]
A different image appears sometimes in what you have uploaded. So image appears in the wrong place.

**Comment by Woseseltops** [comment]
To do as we discussed (not exhaustive, there might be more needed to get this working):
* add boolean 'stub' field to publication
* a view create_stub, which creates publications with stub=True and returns the pk of the newly created object
* when the users starts with creating a publication, do an ajax call to this create_stub page, and save the returned pk to a var
* when saving a new publication, include the pk of the stub, instead of creating a new Django object, extend the stub and set stub=False
* in the list view, make sure to only show publications that have stub==False
* when creating a new uploaded file, include the pk of the stub (or the pk of an existing publication in case you are editing), and use that to make the link automatically
* the modal already automatically sends back a table with the new uploaded files... make sure to filter on the uploaded files linked to the publication we are working on (filtering on the pk)

**Comment by Woseseltops** [comment]
Done:
* add boolean 'stub' field to publication
* a view create_stub, which creates publications with stub=True and returns the pk of the newly created object
* when the users starts with creating a publication, do an ajax call to this create_stub page, and save the returned pk to a var
* when creating a new uploaded file, include the pk of the stub (or the pk of an existing publication in case you are editing), and use that to make the link automatically

Todo, in order of importance:
> in the list view, make sure to only show publications that have stub==False

So the list views don't get polluted.

> when saving a new publication, include the pk of the stub, instead of creating a new Django object, extend the stub and set stub=False

Now, two publications are created.

-- Before continuing with the last todo item #90 --

> the modal already automatically sends back a table with the new uploaded files... make sure to filter on the uploaded files linked to the publication we are working on (filtering on the pk)

Table sometimes doesn't work... during edit?

**Comment by Woseseltops** [comment]
Every now and then the HTML table in the response does not work, @Mergpijp plans to rebuild some of the functionality with pure JQuery.

**Comment by Elisagig** [comment]
Thanks for letting us know
